#!/bin/bash
# dummy file by TheOrangeCat
# your /etc/enviromment or /etc/profile should have kagami dir in path variable
case "$1" in
installpkg)
installpkg $2 $3 $4 $5 $6
;;
removepkg)
removepkg $2 $3 $4 $5 $6
;;
craftpkg)
craftpkg $2 $3 $4 $5 $6
;;
*)
echo "Usage: kagami {installpkg|removepkg|craftpkg} options"
exit 1
;;
esac
